spring:
  application:
    name: discovery-service
  security:
    user:
      name:
      password:

server:
  port: 8761
  shutdown: graceful

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
