name: discovery-service ci/cd

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests

      - name: Copy to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "==> Removing old files..."
            sudo rm -rf ~/discovery-service
          
            echo "==> Creating discovery-service directory..."
            sudo mkdir -p ~/discovery-service
            sudo chmod -R 777 ~/discovery-service
          
            echo "==> Cloning repository..."
            sudo git clone https://github.com/caboom-log/discovery-service.git ~/discovery-service
          
            cd ~/discovery-service
            
            echo "==> Preparing target directory..."
            sudo mkdir -p target/classes
            sudo chmod -R 777 target
          
            echo "==> Building discovery service..."
            sudo ./mvnw clean package -DskipTests
          
            echo "==> Building Docker image..."
            sudo docker build -t caboomlog-discovery-service:latest .
          
            echo "==> Restarting discovery-service..."
            cd /caboomlog
            sudo docker-compose --env-file ~/discovery-service/.env restart discovery-service

